name: AutoVote Workflow

on:
  schedule:
    - cron: "0 0 * * *" # Adjust this for desired schedule
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20 # Match the required Go version

      - name: Install dependencies
        run: go mod tidy

      - name: Run AutoVote
        run: go run main.go
